=== eclipse-openj9/openj9/test/TestConfig/playlist.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<!--
  Copyright (c) 2017, 2018 IBM Corp. and others

  This program and the accompanying materials are made available under
  the terms of the Eclipse Public License 2.0 which accompanies this
  distribution and is available at https://www.eclipse.org/legal/epl-2.0/
  or the Apache License, Version 2.0 which accompanies this distribution and
  is available at https://www.apache.org/licenses/LICENSE-2.0.

  This Source Code may also be made available under the following
  Secondary Licenses when the conditions for such availability set
  forth in the Eclipse Public License, v. 2.0 are satisfied: GNU
  General Public License, version 2 with the GNU Classpath
  Exception [1] and GNU General Public License, version 2 with the
  OpenJDK Assembly Exception [2].

  [1] https://www.gnu.org/software/classpath/license.html
  [2] http://openjdk.java.net/legal/assembly-exception.html

  SPDX-License-Identifier: EPL-2.0 OR Apache-2.0 OR GPL-2.0 WITH Classpath-exception-2.0 OR LicenseRef-GPL-2.0 WITH Assembly-exception
-->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="playlist">
    <xs:complexType>
      <xs:sequence>
        <xs:element type="xs:string" name="include" minOccurs="0"/>
        <xs:element name="test" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:all>
              <xs:element type="xs:string" name="testCaseName"/>
              <xs:element name="variations" minOccurs="0" >
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="variation" maxOccurs="unbounded" minOccurs="0"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element type="xs:string" name="command"/>
              <xs:element type="xs:string" name="disabled" minOccurs="0"/>
              <xs:element type="xs:string" name="capabilities" minOccurs="0"/>
              <xs:element type="xs:string" name="platformRequirements" minOccurs="0"/>
              <xs:element name="tags" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="tag" maxOccurs="unbounded"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="levels" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="level" maxOccurs="unbounded"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="groups" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="group" maxOccurs="unbounded"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="impls" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="impl" maxOccurs="unbounded"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="subsets" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="subset" maxOccurs="unbounded"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:all>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== eclipse-openj9/openj9/test/functional/cmdLineTests/J9security/playlist.xml
<?xml version='1.0' encoding='UTF-8'?>
<!--
  Copyright IBM Corp. and others 2016

  This program and the accompanying materials are made available under
  the terms of the Eclipse Public License 2.0 which accompanies this
  distribution and is available at https://www.eclipse.org/legal/epl-2.0/
  or the Apache License, Version 2.0 which accompanies this distribution and
  is available at https://www.apache.org/licenses/LICENSE-2.0.

  This Source Code may also be made available under the following
  Secondary Licenses when the conditions for such availability set
  forth in the Eclipse Public License, v. 2.0 are satisfied: GNU
  General Public License, version 2 with the GNU Classpath
  Exception [1] and GNU General Public License, version 2 with the
  OpenJDK Assembly Exception [2].

  [1] https://www.gnu.org/software/classpath/license.html
  [2] https://openjdk.org/legal/assembly-exception.html

  SPDX-License-Identifier: EPL-2.0 OR Apache-2.0 OR GPL-2.0-only WITH Classpath-exception-2.0 OR GPL-2.0-only WITH OpenJDK-assembly-exception-1.0
-->
<playlist xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../TKG/resources/playlist.xsd">
	<include>../variables.mk</include>
	<test>
		<testCaseName>cmdLineTester_J9securityTests_SE80</testCaseName>
		<variations>
			<variation>NoOptions</variation>
		</variations>
		<command>$(JAVA_COMMAND) $(CMDLINETESTER_JVM_OPTIONS) -Xdump \
		-DMODULE_ADDEXPORTS_OPTION= -DMODULE_ADDEXPORTS_VALUE= \
		-DTESTJ9SECURITYJARPATH=$(Q)$(TEST_RESROOT)$(D)$(Q) -DRESJAR=$(CMDLINETESTER_RESJAR) \
		-DEXE=$(SQ)$(JAVA_COMMAND) $(JVM_OPTIONS) -Xdump$(SQ) -jar $(CMDLINETESTER_JAR) -config $(Q)$(TEST_RESROOT)$(D)j9SecurityTest.xml$(Q) \
		-explainExcludes -nonZeroExitWhenError; \
		$(TEST_STATUS)</command>
		<levels>
			<level>sanity</level>
		</levels>
		<groups>
			<group>functional</group>
		</groups>
		<versions>
			<version>8</version>
		</versions>
		<impls>
			<impl>openj9</impl>
			<impl>ibm</impl>
		</impls>
	</test>

	<test>
		<testCaseName>cmdLineTester_J9securityTests</testCaseName>
		<variations>
			<variation>NoOptions</variation>
		</variations>
		<command>$(JAVA_COMMAND) $(CMDLINETESTER_JVM_OPTIONS) -Xdump \
		-DMODULE_ADDEXPORTS_OPTION=$(Q)--add-exports$(Q) -DMODULE_ADDEXPORTS_VALUE=$(Q)java.base/jdk.internal.org.objectweb.asm=ALL-UNNAMED$(Q) \
		-DTESTJ9SECURITYJARPATH=$(Q)$(TEST_RESROOT)$(D)$(Q) -DRESJAR=$(CMDLINETESTER_RESJAR) \
		-DEXE=$(SQ)$(JAVA_COMMAND) $(JAVA_SECURITY_MANAGER) $(JVM_OPTIONS) -Xdump$(SQ) -jar $(CMDLINETESTER_JAR) -config $(Q)$(TEST_RESROOT)$(D)j9SecurityTest.xml$(Q) \
		-explainExcludes -nonZeroExitWhenError; \
		$(TEST_STATUS)</command>
		<levels>
			<level>sanity</level>
		</levels>
		<groups>
			<group>functional</group>
		</groups>
		<versions>
			<version>[11,23]</version>
		</versions>
		<impls>
			<impl>openj9</impl>
			<impl>ibm</impl>
		</impls>
	</test>
</playlist>

=== eclipse-openj9/openj9/test/functional/cmdLineTests/shareClassTests/StoreFilterTests/playlist.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
  Copyright (c) 2016, 2019 IBM Corp. and others

  This program and the accompanying materials are made available under
  the terms of the Eclipse Public License 2.0 which accompanies this
  distribution and is available at https://www.eclipse.org/legal/epl-2.0/
  or the Apache License, Version 2.0 which accompanies this distribution and
  is available at https://www.apache.org/licenses/LICENSE-2.0.

  This Source Code may also be made available under the following
  Secondary Licenses when the conditions for such availability set
  forth in the Eclipse Public License, v. 2.0 are satisfied: GNU
  General Public License, version 2 with the GNU Classpath
  Exception [1] and GNU General Public License, version 2 with the
  OpenJDK Assembly Exception [2].

  [1] https://www.gnu.org/software/classpath/license.html
  [2] http://openjdk.java.net/legal/assembly-exception.html

  SPDX-License-Identifier: EPL-2.0 OR Apache-2.0 OR GPL-2.0 WITH Classpath-exception-2.0 OR LicenseRef-GPL-2.0 WITH Assembly-exception
-->

<playlist xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../TestConfig/playlist.xsd">
	<include>variables.mk</include>
	<test>
		<testCaseName>cmdLineTester_StoreFilterTests_win</testCaseName>
		<variations>
			<variation>Mode110</variation>
		</variations>
		<command>cp $(Q)$(TEST_RESROOT)$(D)StoreFilterTests.jar$(Q) .; \
	$(Q)$(TEST_JDK_HOME)$(D)bin$(D)jar.exe$(Q) xf StoreFilterTests.jar; \
	$(JAVA_COMMAND) $(JVM_OPTIONS) -DJAVA_EXE=$(SQ)$(JAVA_COMMAND) $(JVM_OPTIONS)$(SQ) -DPD=$(Q)\\$(Q) -DTEST_JDK_HOME=$(Q)$(TEST_JDK_HOME)$(Q) -DCPDL=$(Q)$(P)$(Q) -DRUN_SCRIPT=$(Q)cmd /c$(Q) -DSCRIPT_SUFFIX=.bat -DSCMODE=204 \
	-jar $(CMDLINETESTER_JAR) \
	-config $(Q)$(TEST_RESROOT)$(D)StoreFilterTests$(XMLSUFFIX).xml$(Q) \
	-nonZeroExitWhenError \
	-outputLimit 300; \
	$(TEST_STATUS)</command>
		<platformRequirements>os.win</platformRequirements>
		<levels>
			<level>sanity</level>
		</levels>
		<groups>
			<group>functional</group>
		</groups>
		<aot>explicit</aot>
		<impls>
			<impl>openj9</impl>
			<impl>ibm</impl>
		</impls>
	</test>
	<test>
		<testCaseName>cmdLineTester_StoreFilterTests_unix</testCaseName>
		<variations>
			<variation>Mode110</variation>
		</variations>
		<command>cp $(Q)$(TEST_RESROOT)$(D)StoreFilterTests.jar$(Q) .; \
	$(Q)$(TEST_JDK_HOME)$(D)bin$(D)jar$(Q) xf StoreFilterTests.jar; \
	$(JAVA_COMMAND) $(JVM_OPTIONS) -DJAVA_EXE=$(SQ)$(JAVA_COMMAND) $(JVM_OPTIONS)$(SQ) -DPD=$(Q)/$(Q) -DTEST_JDK_HOME=$(Q)$(TEST_JDK_HOME)$(Q) -DCPDL=$(Q)$(P)$(Q) -DRUN_SCRIPT=$(Q)sh$(Q) -DSCRIPT_SUFFIX=.sh -DSCMODE=204 \
	-jar $(CMDLINETESTER_JAR) \
	-config $(Q)$(TEST_RESROOT)$(D)StoreFilterTests$(XMLSUFFIX).xml$(Q) \
	-nonZeroExitWhenError \
	-outputLimit 300; \
	$(TEST_STATUS)</command>
		<platformRequirements>^os.win,^os.zos</platformRequirements>
		<levels>
			<level>sanity</level>
		</levels>
		<groups>
			<group>functional</group>
		</groups>
		<aot>explicit</aot>
		<impls>
			<impl>openj9</impl>
			<impl>ibm</impl>
		</impls>		
	</test>
</playlist>

=== eclipse-openj9/openj9/test/functional/VM_Test/playlist.xml
<?xml version='1.0' encoding='UTF-8'?>
<!--
Copyright IBM Corp. and others 2016

This program and the accompanying materials are made available under
the terms of the Eclipse Public License 2.0 which accompanies this
distribution and is available at https://www.eclipse.org/legal/epl-2.0/
or the Apache License, Version 2.0 which accompanies this distribution and
is available at https://www.apache.org/licenses/LICENSE-2.0.

This Source Code may also be made available under the following
Secondary Licenses when the conditions for such availability set
forth in the Eclipse Public License, v. 2.0 are satisfied: GNU
General Public License, version 2 with the GNU Classpath
Exception [1] and GNU General Public License, version 2 with the
OpenJDK Assembly Exception [2].

[1] https://www.gnu.org/software/classpath/license.html
[2] https://openjdk.org/legal/assembly-exception.html

SPDX-License-Identifier: EPL-2.0 OR Apache-2.0 OR GPL-2.0 WITH Classpath-exception-2.0 OR LicenseRef-GPL-2.0 WITH Assembly-exception
-->
<playlist xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../TKG/playlist.xsd">
	<test>
		<testCaseName>J9vmTest</testCaseName>
		<variations>
			<variation>Mode110</variation>
			<variation>Mode301</variation>
			<variation>Mode351</variation>
			<variation>Mode501</variation>
			<variation>Mode551</variation>
			<variation>Mode610</variation>
		</variations>
		<command>$(ADD_JVM_LIB_DIR_TO_LIBPATH) \
	$(JAVA_COMMAND) $(JVM_OPTIONS) -Xdump -Xint \
	-cp $(Q)$(TEST_RESROOT)$(D)VM_Test.jar$(P)$(LIB_DIR)$(D)asm-all.jar$(Q) \
	j9vm.runner.Menu A -exe=$(SQ)$(TEST_JDK_HOME)$(D)bin$(D)java $(JVM_OPTIONS) -Xdump$(SQ) -version=$(JDK_VERSION) -jar=$(Q)$(TEST_RESROOT)$(D)VM_Test.jar$(Q) -xlist=$(Q)$(TEST_RESROOT)$(D)j9vm.xml$(Q) \
	-xids=all,$(PLATFORM); \
	$(TEST_STATUS)</command>
		<levels>
			<level>sanity</level>
		</levels>
		<groups>
			<group>functional</group>
		</groups>
		<types>
			<type>native</type>
		</types>
		<impls>
			<impl>openj9</impl>
			<impl>ibm</impl>
		</impls>
	</test>
	<test>
		<testCaseName>jvmnativestest</testCaseName>
		<command>$(ADD_JVM_LIB_DIR_TO_LIBPATH) \
	$(JAVA_COMMAND) $(JVM_OPTIONS) \
	-cp $(Q)$(TEST_RESROOT)$(D)VM_Test.jar$(P)$(LIB_DIR)$(D)junit4.jar$(Q) \
	com.ibm.oti.jvmtests.AutoRun; \
	$(TEST_STATUS)</command>
		<levels>
			<level>sanity</level>
		</levels>
		<groups>
			<group>functional</group>
		</groups>
		<types>
			<type>native</type>
		</types>
		<versions>
			<version>11+</version>
		</versions>
		<impls>
			<impl>openj9</impl>
			<impl>ibm</impl>
		</impls>
	</test>
	<test>
		<testCaseName>ThreadRegressionTests</testCaseName>
		<variations>
			<variation>Mode110</variation>
			<variation>Mode201</variation>
			<variation>Mode301</variation>
			<variation>Mode351</variation>
			<variation>Mode610</variation>
		</variations>
		<command>$(JAVA_COMMAND) $(JVM_OPTIONS) \
	-cp $(Q)$(TEST_RESROOT)$(D)VM_Test.jar$(P)$(LIB_DIR)$(D)junit4.jar$(Q) \
	j9vm.test.threads.regression.RegressionTests $(Q)$(TEST_RESROOT)$(Q); \
	$(TEST_STATUS)</command>
		<levels>
			<level>extended</level>
		</levels>
		<groups>
			<group>functional</group>
		</groups>
		<impls>
			<impl>openj9</impl>
			<impl>ibm</impl>
		</impls>
	</test>
	<test>
		<testCaseName>SharedClassesSysVTesting</testCaseName>
		<command>perl $(JVM_TEST_ROOT)$(D)TestConfig$(D)scripts$(D)tools$(D)sysvcleanup.pl all ; \
	cd $(TEST_JDK_HOME)$(D)bin ; \
	perl $(TEST_RESROOT)$(D)SharedClassesSysVTesting$(D)testSC_SysV_Java7_Tests.pl linux ; \
	$(TEST_STATUS)</command>
		<platformRequirements>os.linux,^arch.390</platformRequirements>
		<levels>
			<level>sanity</level>
		</levels>
		<groups>
			<group>functional</group>
		</groups>
		<impls>
			<impl>openj9</impl>
			<impl>ibm</impl>
		</impls>
	</test>
	<test>
		<testCaseName>recreateClassTest</testCaseName>
		<disables>
			<disable>
				<comment>excluded OpenJ9 tests</comment>
			</disable>
		</disables>
		<variations>
			<variation>NoOptions</variation>
		</variations>
		<command>$(JAVA_COMMAND) $(JVM_OPTIONS) \
	-javaagent:$(Q)$(TEST_RESROOT)$(D)VM_Test.jar$(Q) \
	-cp $(Q)$(LIB_DIR)$(D)junit4.jar$(P)$(LIB_DIR)$(D)asm-all.jar$(P)$(TEST_RESROOT)$(D)VM_Test.jar$(P)$(LIB_DIR)$(D)javassist.jar$(Q) \
	junit.textui.TestRunner com.ibm.j9.recreateclass.tests.RecreateClassTestSuite; \
	$(TEST_STATUS)</command>
		<levels>
			<level>sanity</level>
		</levels>
		<groups>
			<group>functional</group>
		</groups>
		<versions>
			<version>8</version>
		</versions>
		<impls>
			<impl>openj9</impl>
			<impl>ibm</impl>
		</impls>
	</test>
	<test>
		<testCaseName>CFdumptest</testCaseName>
		<disables>
			<disable>
				<comment>excluded OpenJ9 tests</comment>
			</disable>
		</disables>
		<command>$(JAVA_COMMAND) $(JVM_OPTIONS) \
	-cp $(Q)$(TEST_RESROOT)$(D)VM_Test.jar$(P)$(LIB_DIR)$(D)junit4.jar$(Q) \
	junit.textui.TestRunner com.ibm.j9.cfdump.tests.CfdumpTestSuite; \
	$(TEST_STATUS)</command>
		<levels>
			<level>sanity</level>
		</levels>
		<groups>
			<group>functional</group>
		</groups>
		<versions>
			<version>8</version>
		</versions>
		<impls>
			<impl>openj9</impl>
			<impl>ibm</impl>
		</impls>
	</test>
	<test>
		<testCaseName>j9vmClassUnloading</testCaseName>
		<variations>
			<variation>Mode110</variation>
			<variation>Mode301</variation>
			<variation>Mode351</variation>
			<variation>Mode501</variation>
			<variation>Mode551</variation>
			<variation>Mode610</variation>
		</variations>
		<command>$(JAVA_COMMAND) -Xdump -Xint -Dj9vm.testing.tests.path=$(TEST_RESROOT) \
	-cp $(Q)$(TEST_RESROOT)$(D)VM_Test.jar$(P)$(LIB_DIR)$(D)asm-all.jar$(Q)  \
	j9vm.runner.Menu -exe=$(Q)$(JAVA_COMMAND) $(JVM_OPTIONS) -Xdump$(Q) -jar=$(Q)$(TEST_RESROOT)$(D)VM_Test.jar$(Q) -test=$(Q)j9vm.test.classunloading.testcases$(Q) \
	-xids=all,$(PLATFORM),$(VARIATION); \
	$(TEST_STATUS)</command>
		<levels>
			<level>extended</level>
		</levels>
		<groups>
			<group>functional</group>
		</groups>
		<impls>
			<impl>openj9</impl>
			<impl>ibm</impl>
		</impls>
	</test>
	<test>
		<testCaseName>xlpTests</testCaseName>
		<disables>
			<disable>
				<comment>https://github.com/eclipse-openj9/openj9/issues/11374</comment>
				<platform>.*mac.*</platform>
			</disable>
		</disables>
		<variations>
			<variation>Mode110</variation>
			<variation>Mode610</variation>
		</variations>
		<command>$(JAVA_COMMAND) -Dplatform=$(PLATFORM) -cp $(Q)$(TEST_RESROOT)$(D)VM_Test.jar$(Q) \
	j9vm.runner.Menu -test=$(Q)j9vm.test.xlp$(Q) -exe=$(Q)$(JAVA_COMMAND) $(JVM_OPTIONS) -Xdump$(Q) \
	-jar=$(Q)$(TEST_RESROOT)$(D)VM_Test.jar$(Q) \
	-xids=all,$(PLATFORM),$(VARIATION); \
	$(TEST_STATUS)</command>
		<levels>
			<level>extended</level>
		</levels>
		<groups>
			<group>functional</group>
		</groups>
		<impls>
			<impl>openj9</impl>
			<impl>ibm</impl>
		</impls>
	</test>
	<test>
		<testCaseName>xlpCodeCacheTests</testCaseName>
		<variations>
			<variation>Mode109</variation>
			<variation>Mode110</variation>
			<variation>Mode609</variation>
			<variation>Mode610</variation>
		</variations>
		<command>$(JAVA_COMMAND) -Dplatform=$(PLATFORM) -cp $(Q)$(TEST_RESROOT)$(D)VM_Test.jar$(Q) \
	j9vm.runner.Menu -test=$(Q)j9vm.test.xlpcodecache$(Q) -exe=$(Q)$(JAVA_COMMAND) $(JVM_OPTIONS) -Xdump$(Q) \
	-jar=$(Q)$(TEST_RESROOT)$(D)VM_Test.jar$(Q) \
	-xids=all,$(PLATFORM),$(VARIATION); \
	$(TEST_STATUS)</command>
		<levels>
			<level>extended</level>
		</levels>
		<groups>
			<group>functional</group>
		</groups>
		<impls>
			<impl>openj9</impl>
			<impl>ibm</impl>
		</impls>
	</test>
</playlist>

=== eclipse-openj9/openj9/test/functional/cmdLineTests/xcheckjni/playlist.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
  Copyright (c) 2016, 2019 IBM Corp. and others

  This program and the accompanying materials are made available under
  the terms of the Eclipse Public License 2.0 which accompanies this
  distribution and is available at https://www.eclipse.org/legal/epl-2.0/
  or the Apache License, Version 2.0 which accompanies this distribution and
  is available at https://www.apache.org/licenses/LICENSE-2.0.

  This Source Code may also be made available under the following
  Secondary Licenses when the conditions for such availability set
  forth in the Eclipse Public License, v. 2.0 are satisfied: GNU
  General Public License, version 2 with the GNU Classpath
  Exception [1] and GNU General Public License, version 2 with the
  OpenJDK Assembly Exception [2].

  [1] https://www.gnu.org/software/classpath/license.html
  [2] http://openjdk.java.net/legal/assembly-exception.html

  SPDX-License-Identifier: EPL-2.0 OR Apache-2.0 OR GPL-2.0 WITH Classpath-exception-2.0 OR LicenseRef-GPL-2.0 WITH Assembly-exception
-->

<playlist xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../TestConfig/playlist.xsd">
	<test>
		<testCaseName>cmdLineTester_XcheckJNI</testCaseName>
		<variations>
			<variation>NoOptions</variation>
		</variations>
		<command>$(ADD_JVM_LIB_DIR_TO_LIBPATH) \
	$(JAVA_COMMAND) -DRESJAR=$(CMDLINETESTER_RESJAR) -DEXE=$(SQ)$(JAVA_COMMAND)$(SQ) -Xint -jar $(CMDLINETESTER_JAR) \
	-config $(Q)$(TEST_RESROOT)$(D)xcheckjni.xml$(Q) -nonZeroExitWhenError; \
	$(TEST_STATUS)</command>
		<levels>
			<level>sanity</level>
		</levels>
		<groups>
			<group>functional</group>
		</groups>
		<types>
			<type>native</type>
		</types>
		<impls>
			<impl>openj9</impl>
			<impl>ibm</impl>
		</impls>
	</test>
</playlist>

=== eclipse-openj9/openj9/test/cmdLineTests/classesdbgddrext/playlist.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
  Copyright (c) 2017, 2017 IBM Corp. and others

  This program and the accompanying materials are made available under
  the terms of the Eclipse Public License 2.0 which accompanies this
  distribution and is available at https://www.eclipse.org/legal/epl-2.0/
  or the Apache License, Version 2.0 which accompanies this distribution and
  is available at https://www.apache.org/licenses/LICENSE-2.0.

  This Source Code may also be made available under the following
  Secondary Licenses when the conditions for such availability set
  forth in the Eclipse Public License, v. 2.0 are satisfied: GNU
  General Public License, version 2 with the GNU Classpath
  Exception [1] and GNU General Public License, version 2 with the
  OpenJDK Assembly Exception [2].

  [1] https://www.gnu.org/software/classpath/license.html
  [2] http://openjdk.java.net/legal/assembly-exception.html

  SPDX-License-Identifier: EPL-2.0 OR Apache-2.0 OR GPL-2.0 WITH Classpath-exception-2.0 OR LicenseRef-GPL-2.0 WITH Assembly-exception
-->

<playlist xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../TestConfig/playlist.xsd">
	<test>
		<testCaseName>cmdLineTester_classesdbgddrext_zos</testCaseName>
		<variations>
			<variation>NoOptions</variation>
		</variations>
		<command>perl $(JVM_TEST_ROOT)$(D)TestConfig$(D)scripts$(D)tools$(D)sysvcleanup.pl zos ; \
	$(JAVA_COMMAND) $(JVM_OPTIONS) -Xmx1G \
	-DRESJAR=$(CMDLINETESTER_RESJAR) \
	-DEXE='$(JAVA_COMMAND) $(JVM_OPTIONS)' \
	-DJDMPVIEW_EXE="$(JAVA_BIN)$(D)jdmpview" \
	-DUTILSJAR=$(Q)$(JVM_TEST_ROOT)$(D)cmdLineTests$(D)utils$(D)utils.jar$(Q) \
	-jar $(CMDLINETESTER_JAR) \
	-config $(Q)$(TEST_RESROOT)$(D)classesddrtests.xml$(Q) \
	-outputLimit 1000 -explainExcludes -xids all,$(PLATFORM),$(VARIATION) -plats all,$(PLATFORM),$(VARIATION) \
	-xlist $(Q)$(TEST_RESROOT)$(D)dbgextddrtests_excludes.xml$(Q) -nonZeroExitWhenError; \
	${TEST_STATUS}</command>
		<platformRequirements>os.zos</platformRequirements>
		<tags>
			<tag>extended</tag>
		</tags>
		<subsets>
			<subset>SE80</subset>
			<subset>SE90</subset>
		</subsets>
	</test>

	<test>
		<testCaseName>cmdLineTester_classesdbgddrext</testCaseName>
		<variations>
			<variation>Mode110</variation>
			<variation>Mode610</variation>
		</variations>
		<command>perl $(JVM_TEST_ROOT)$(D)TestConfig$(D)scripts$(D)tools$(D)sysvcleanup.pl all ; \
	$(JAVA_COMMAND) $(JVM_OPTIONS) -Xmx1G \
	-DRESJAR=$(CMDLINETESTER_RESJAR) \
	-DEXE='$(JAVA_COMMAND) $(JVM_OPTIONS)' \
	-DJDMPVIEW_EXE="$(JAVA_BIN)$(D)jdmpview" \
	-DUTILSJAR=$(Q)$(JVM_TEST_ROOT)$(D)cmdLineTests$(D)utils$(D)utils.jar$(Q) \
	-jar $(CMDLINETESTER_JAR) \
	-config $(Q)$(TEST_RESROOT)$(D)classesddrtests.xml$(Q) \
	-outputLimit 1000 -explainExcludes -xids all,$(PLATFORM),$(VARIATION) -plats all,$(PLATFORM),$(VARIATION) \
	-xlist $(Q)$(TEST_RESROOT)$(D)dbgextddrtests_excludes.xml$(Q) -nonZeroExitWhenError; \
	${TEST_STATUS}</command>
		<platformRequirements>^os.zos,^os.zos</platformRequirements>
		<tags>
			<tag>extended</tag>
		</tags>
		<subsets>
			<subset>SE80</subset>
			<subset>SE90</subset>
		</subsets>
	</test>
	<test>
		<testCaseName>cmdLineTester_classesdbgddrext_aix</testCaseName>
		<variations>
			<variation>Mode110</variation>
			<variation>Mode610</variation>
		</variations>
		<command>perl $(JVM_TEST_ROOT)$(D)TestConfig$(D)scripts$(D)tools$(D)sysvcleanup.pl aix ; \
	$(JAVA_COMMAND) $(JVM_OPTIONS) -Xmx1G \
	-DRESJAR=$(CMDLINETESTER_RESJAR) \
	-DEXE='$(JAVA_COMMAND) $(JVM_OPTIONS)' \
	-DJDMPVIEW_EXE="$(JAVA_BIN)$(D)jdmpview" \
	-DUTILSJAR=$(Q)$(JVM_TEST_ROOT)$(D)cmdLineTests$(D)utils$(D)utils.jar$(Q) \
	-jar $(CMDLINETESTER_JAR) \
	-config $(Q)$(TEST_RESROOT)$(D)classesddrtests.xml$(Q) \
	-outputLimit 1000 -explainExcludes -xids all,$(PLATFORM),$(VARIATION) -plats all,$(PLATFORM),$(VARIATION) \
	-xlist $(Q)$(TEST_RESROOT)$(D)dbgextddrtests_excludes.xml$(Q) -nonZeroExitWhenError; \
	${TEST_STATUS}</command>
		<platformRequirements>os.aix</platformRequirements>
		<tags>
			<tag>extended</tag>
		</tags>
		<subsets>
			<subset>SE80</subset>
			<subset>SE90</subset>
		</subsets>
	</test>


</playlist>

=== eclipse-openj9/openj9/test/functional/Jsr335/playlist.xml
<?xml version='1.0' encoding='UTF-8'?>
<!--
  Copyright IBM Corp. and others 2016

  This program and the accompanying materials are made available under
  the terms of the Eclipse Public License 2.0 which accompanies this
  distribution and is available at https://www.eclipse.org/legal/epl-2.0/
  or the Apache License, Version 2.0 which accompanies this distribution and
  is available at https://www.apache.org/licenses/LICENSE-2.0.

  This Source Code may also be made available under the following
  Secondary Licenses when the conditions for such availability set
  forth in the Eclipse Public License, v. 2.0 are satisfied: GNU
  General Public License, version 2 with the GNU Classpath
  Exception [1] and GNU General Public License, version 2 with the
  OpenJDK Assembly Exception [2].

  [1] https://www.gnu.org/software/classpath/license.html
  [2] https://openjdk.org/legal/assembly-exception.html

  SPDX-License-Identifier: EPL-2.0 OR Apache-2.0 OR GPL-2.0 WITH Classpath-exception-2.0 OR LicenseRef-GPL-2.0 WITH Assembly-exception
-->
<playlist xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../TKG/playlist.xsd">
	<test>
		<testCaseName>jsr335tests_SE80</testCaseName>
		<variations>
			<variation>Mode100</variation>
			<variation>Mode600</variation>
			<variation>Mode101</variation>
			<variation>Mode601</variation>
			<variation>Mode110</variation>
			<variation>Mode610</variation>
			<variation>Mode301</variation>
			<variation>Mode501</variation>
		</variations>
		<command>$(JAVA_COMMAND) $(JVM_OPTIONS) \
	-cp $(Q)$(RESOURCES_DIR)$(P)$(TESTNG)$(P)$(LIB_DIR)$(D)junit4.jar$(P)$(LIB_DIR)$(D)asm-all.jar$(P)$(TEST_RESROOT)$(D)Jsr335.jar$(P).$(Q) \
	org.testng.TestNG -d $(REPORTDIR) $(Q)$(TEST_RESROOT)$(D)testng.xml$(Q) -testnames jsr335 \
	-groups $(TEST_GROUP) \
	-excludegroups $(DEFAULT_EXCLUDE); \
	$(TEST_STATUS)</command>
		<versions>
			<version>8</version>
		</versions>
		<levels>
			<level>sanity</level>
		</levels>
		<groups>
			<group>functional</group>
		</groups>
		<impls>
			<impl>openj9</impl>
			<impl>ibm</impl>
		</impls>
	</test>
	<test>
		<testCaseName>jsr335tests</testCaseName>
		<variations>
			<variation>Mode100</variation>
			<variation>Mode600</variation>
			<variation>Mode101</variation>
			<variation>Mode601</variation>
			<variation>Mode110</variation>
			<variation>Mode610</variation>
			<variation>Mode301</variation>
			<variation>Mode501</variation>
		</variations>
		<command>$(JAVA_COMMAND) $(JVM_OPTIONS) --add-opens=java.base/java.lang.invoke=ALL-UNNAMED \
	--add-exports java.base/jdk.internal.misc=ALL-UNNAMED --add-opens=java.base/jdk.internal.misc=ALL-UNNAMED \
	-cp $(Q)$(RESOURCES_DIR)$(P)$(TESTNG)$(P)$(LIB_DIR)$(D)junit4.jar$(P)$(LIB_DIR)$(D)asm-all.jar$(P)$(TEST_RESROOT)$(D)Jsr335.jar$(P).$(Q) \
	org.testng.TestNG -d $(REPORTDIR) $(Q)$(TEST_RESROOT)$(D)testng.xml$(Q) -testnames jsr335 \
	-groups $(TEST_GROUP) \
	-excludegroups $(DEFAULT_EXCLUDE); \
	$(TEST_STATUS)</command>
		<versions>
			<version>9+</version>
		</versions>
		<levels>
			<level>sanity</level>
		</levels>
		<groups>
			<group>functional</group>
		</groups>
		<impls>
			<impl>openj9</impl>
			<impl>ibm</impl>
		</impls>
	</test>
	<test>
		<testCaseName>jsr335tests_none_SCC</testCaseName>
		<variations>
			<variation>Mode100</variation>
			<variation>Mode600</variation>
			<variation>Mode101</variation>
			<variation>Mode601</variation>
			<variation>Mode110</variation>
			<variation>Mode610</variation>
			<variation>Mode301</variation>
			<variation>Mode501</variation>
		</variations>
		<command>$(JAVA_COMMAND) $(JVM_OPTIONS) -Xshareclasses:none --add-opens=java.base/java.lang.invoke=ALL-UNNAMED \
	--add-exports java.base/jdk.internal.misc=ALL-UNNAMED --add-opens=java.base/jdk.internal.misc=ALL-UNNAMED \
	-cp $(Q)$(RESOURCES_DIR)$(P)$(TESTNG)$(P)$(LIB_DIR)$(D)junit4.jar$(P)$(LIB_DIR)$(D)asm-all.jar$(P)$(TEST_RESROOT)$(D)Jsr335.jar$(P).$(Q) \
	org.testng.TestNG -d $(REPORTDIR) $(Q)$(TEST_RESROOT)$(D)testng.xml$(Q) -testnames jsr335 \
	-groups $(TEST_GROUP) \
	-excludegroups $(DEFAULT_EXCLUDE); \
	$(TEST_STATUS)</command>
		<versions>
			<version>9+</version>
		</versions>
		<levels>
			<level>sanity</level>
		</levels>
		<groups>
			<group>functional</group>
		</groups>
		<impls>
			<impl>openj9</impl>
			<impl>ibm</impl>
		</impls>
	</test>
	<test>
		<testCaseName>jsr335tests_defendersupersends_SE80</testCaseName>
		<variations>
			<variation>Mode100</variation>
		</variations>
		<command>$(JAVA_COMMAND) $(JVM_OPTIONS) \
	-cp $(Q)$(RESOURCES_DIR)$(P)$(TESTNG)$(P)$(LIB_DIR)$(D)junit4.jar$(P)$(LIB_DIR)$(D)asm-all.jar$(P)$(TEST_RESROOT)$(D)Jsr335.jar$(P).$(Q) \
	org.openj9.test.jsr335.defendersupersends.TestDefenderSupersends; \
	$(TEST_STATUS)</command>
		<levels>
			<level>sanity</level>
		</levels>
		<groups>
			<group>functional</group>
		</groups>
		<versions>
			<version>8</version>
		</versions>
		<impls>
			<impl>openj9</impl>
			<impl>ibm</impl>
		</impls>
	</test>
	<test>
		<testCaseName>jsr335tests_defendersupersends</testCaseName>
		<variations>
			<variation>Mode100</variation>
		</variations>
		<command>$(JAVA_COMMAND) $(JVM_OPTIONS) --add-opens=java.base/java.lang.invoke=ALL-UNNAMED \
	--add-exports java.base/jdk.internal.misc=ALL-UNNAMED --add-opens=java.base/jdk.internal.misc=ALL-UNNAMED \
	-cp $(Q)$(RESOURCES_DIR)$(P)$(TESTNG)$(P)$(LIB_DIR)$(D)junit4.jar$(P)$(LIB_DIR)$(D)asm-all.jar$(P)$(TEST_RESROOT)$(D)Jsr335.jar$(P).$(Q) \
	org.openj9.test.jsr335.defendersupersends.TestDefenderSupersends; \
	$(TEST_STATUS)</command>
		<levels>
			<level>sanity</level>
		</levels>
		<groups>
			<group>functional</group>
		</groups>
		<versions>
			<version>9+</version>
		</versions>
		<impls>
			<impl>openj9</impl>
			<impl>ibm</impl>
		</impls>
	</test>
</playlist>
